### ISSUE TITLE
20211214 프로젝트 내 '수정하기' 이슈

### ISSUE THREAD

**Issue by ehdqkd616** [htwenty-1/multicampus_study_note#2]
## 개요
사용되지 않는 변수와 메서드는 되도록 제거하는 것이 좋습니다.

## 문제
사용되지 않는 변수와 반복문 -> int i와 for문
[multicampus_study_note/4th Java/20211214/StudentProc/src/dao/StudentDao.java](https://github.com/htwenty-1/multicampus_study_note/blob/f8e48f92762b4a4c7e3ab1396ca04c9fa94d0b8b/4th%20Java/20211214/StudentProc/src/dao/StudentDao.java#L92)
Line 92 in f8e48f9
```
for (int i = 0; i < student.length; i++) {
```
## 개선방향
for문을 사용한 부분을 제거합니다.

**Comment by htwenty-1** [comment]
## Confirmed

Thank you Mr.Kim!

I'm even more honored because it's the first reply you left for me. 

I don't know which logic I touched wrong at first, but it didn't work properly without using iteration.
So I used iteration, but after fixing a few places, I no longer need them.

So thank you for the feedback on the part I didn't delete.

Have a great day! 😉
